#!/usr/bin/env python3
from __future__ import annotations

import json
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Iterable

ROOT = Path("/Volumes/AI/tactics")
ASSET_ROOTS = [
    ROOT / "assets" / "characters",
    ROOT / "assets" / "environment",
    ROOT / "assets" / "props",
]
OUT_JSON = ROOT / "docs" / "generated" / "missing_image_generation_backlog_v01.json"
OUT_MD = ROOT / "docs" / "generated" / "missing_image_generation_backlog_v01.md"


@dataclass
class AssetLaneStatus:
    asset_id: str
    category: str
    path: str
    has_spec: bool
    has_prompt_pack: bool
    source_png_count: int
    clean_png_count: int
    runtime_png_count: int
    missing_steps: list[str]
    generation_ready: bool
    priority: str


def iter_asset_dirs() -> Iterable[Path]:
    for root in ASSET_ROOTS:
        if not root.exists():
            continue
        for spec in sorted(root.glob("*/spec.md")):
            yield spec.parent


def count_pngs(directory: Path) -> int:
    if not directory.exists():
        return 0
    return len(list(directory.rglob("*.png")))


def compute_priority(category: str, missing_steps: list[str]) -> str:
    if not missing_steps:
        return "none"
    if category == "characters":
        if "source" in missing_steps:
            return "high"
        if "clean" in missing_steps:
            return "medium"
        return "medium"
    if category in {"environment", "props"}:
        if "source" in missing_steps:
            return "high"
        if "runtime" in missing_steps:
            return "medium"
        return "low"
    return "low"


def build_status(asset_dir: Path) -> AssetLaneStatus:
    category = asset_dir.parent.name
    source_count = count_pngs(asset_dir / "source")
    clean_count = count_pngs(asset_dir / "clean")
    runtime_count = count_pngs(asset_dir / "runtime")
    prompt_pack = asset_dir / "prompt_pack_v01.md"
    has_spec = (asset_dir / "spec.md").exists()
    missing_steps: list[str] = []
    if source_count == 0:
        missing_steps.append("source")
    if clean_count == 0:
        missing_steps.append("clean")
    if runtime_count == 0:
        missing_steps.append("runtime")
    generation_ready = has_spec and source_count == 0
    return AssetLaneStatus(
        asset_id=asset_dir.name,
        category=category,
        path=str(asset_dir),
        has_spec=has_spec,
        has_prompt_pack=prompt_pack.exists(),
        source_png_count=source_count,
        clean_png_count=clean_count,
        runtime_png_count=runtime_count,
        missing_steps=missing_steps,
        generation_ready=generation_ready,
        priority=compute_priority(category, missing_steps),
    )


def write_markdown(statuses: list[AssetLaneStatus]) -> None:
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    lines.append("# Missing Image Generation Backlog V01")
    lines.append("")
    lines.append("Generated by `scripts/dev/build_missing_image_generation_backlog.py`.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    total = len(statuses)
    missing = [s for s in statuses if s.missing_steps]
    ready = [s for s in statuses if s.generation_ready]
    lines.append(f"- total lanes scanned: `{total}`")
    lines.append(f"- lanes with missing image steps: `{len(missing)}`")
    lines.append(f"- lanes immediately ready for source-image generation: `{len(ready)}`")
    lines.append("")
    lines.append("## Lanes Requiring Work")
    lines.append("")
    if not missing:
        lines.append("- none")
    else:
        for status in sorted(missing, key=lambda s: (s.priority, s.category, s.asset_id)):
            lines.append(f"### `{status.asset_id}`")
            lines.append(f"- category: `{status.category}`")
            lines.append(f"- path: `{status.path}`")
            lines.append(f"- missing: `{', '.join(status.missing_steps)}`")
            lines.append(f"- source pngs: `{status.source_png_count}`")
            lines.append(f"- clean pngs: `{status.clean_png_count}`")
            lines.append(f"- runtime pngs: `{status.runtime_png_count}`")
            lines.append(f"- generation ready: `{'yes' if status.generation_ready else 'no'}`")
            lines.append(f"- priority: `{status.priority}`")
            lines.append("")
    lines.append("## Immediate Generation Queue")
    lines.append("")
    queue = [s for s in ready if s.priority in {"high", "medium"}]
    if not queue:
        lines.append("- no source-generation-ready lanes currently missing source assets")
    else:
        for status in queue:
            lines.append(f"- `{status.asset_id}`")
    lines.append("")
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    statuses = [build_status(asset_dir) for asset_dir in iter_asset_dirs()]
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(
        json.dumps([asdict(s) for s in statuses], indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    write_markdown(statuses)
    print(f"[PASS] wrote {OUT_JSON}")
    print(f"[PASS] wrote {OUT_MD}")


if __name__ == "__main__":
    main()
